services:

  main:
    build:
      args:
        build_env: dev
      context: .
      target: builder
    command: ["sleep", "infinity"]
    ports:
      - "8890:8080"
    volumes:
     - ./app:/project/app
     - ./tests:/project/tests
     - ./htmlcov:/project/htmlcov
     - ./scripts:/project/scripts
     - ./values.env:/project/values.env
