[project]
name = "app"
version = "1.0.0"
description = "A containerized Python && Jupyter environment."
authors = [{name = "Sergey Pavlov", email = "self@sergeypavlov.dev"}]
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.0.0",
    "pandas>=2.0.1",
]

[tool.pdm.dev-dependencies]
dev = [
    "black[jupyter]>=23.3.0",
    "isort>=5.12.0",
    "mypy>=1.3.0",
    "ruff>=0.0.265",
]

[tool.pdm.scripts]
jupyter = "jupyter notebook --allow-root --no-browser --ip 0.0.0.0 --NotebookApp.token='' notebook"
lint = {composite = ["black", "isort", "ruff", "mypy --strict"]} # pdm run lint notebook

[tool.black]
line-length = 100
quiet = true

[tool.isort]
quiet = true
line_length = 100
multi_line_output = 3
profile = "black"

[tool.ruff]
fix = true
line-length = 100
target-version = "py311"

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
