[tool.poetry]
name = "notebook-environment"
version = "0.1.0"
description = ""
authors = ["Sergey Pavlov <self@sergeypavlov.dev>"]

[tool.poetry.dependencies]
python = "~3.10"
jupyter = "*"
jupyterthemes = "*"
pandas = "*"

[tool.poetry.dev-dependencies]
mypy = "*"
flake8 = "*"

[tool.poetry-exec-plugin.commands]
jupyter = "jupyter notebook --allow-root --no-browser --ip 0.0.0.0 --NotebookApp.token=''"