[project]
name = "app"
version = "1.0.0"
description = "Python environment."
authors = [{name = "Sergey Pavlov", email = "self@sergeypavlov.dev"}]
requires-python = ">=3.12"
dependencies = []

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.9.1",
    "isort>=5.12.0",
    "mypy>=1.6.0",
    "ruff>=0.0.292",
]

[tool.pdm.scripts]
lint = {composite = ["black app", "isort app", "ruff app", "mypy app"]}

[tool.black]
line-length = 100
quiet = true

[tool.isort]
quiet = true
line_length = 100
multi_line_output = 3
profile = "black"

[tool.ruff]
fix = true
line-length = 100
target-version = "py312"

[tool.mypy]
strict = true
ignore_missing_imports = true
show_error_codes = true
