[tool.poetry]
name = "notebook-environment"
version = "0.1.0"
description = ""
authors = ["Sergey Pavlov <self@sergeypavlov.dev>"]

[tool.poetry.dependencies]
python = "~3.10"
jupyter = "*"
jupyterthemes = "*"
pandas = "*"

[tool.poetry.dev-dependencies]
autoflake = "*"
black = "*"
flake8 = "*"
flake8-bugbear = "*"
isort = "*"
mypy = "*"

[tool.poetry-exec-plugin.commands]
autoflake = "autoflake -i -r --remove-all-unused-imports"
black = "black --line-length=79"
flake8 = "flake8"
isort = "isort"
jupyter = "jupyter notebook --allow-root --no-browser --ip 0.0.0.0 --NotebookApp.token=''"
mypy = "mypy --strict"

[tool.isort]
multi_line_output = 3
profile = "black"

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
