[project]
name = ""
version = ""
description = ""
authors = [{name = "Sergey Pavlov", email = "self@sergeypavlov.dev"}]
requires-python = ">=3.11"
dependencies = [
    "jupyter",
    "pandas",
]

[tool.pdm.dev-dependencies]
dev = [
    "black[jupyter]",
    "isort",
    "mypy",
    "ruff",
]

[tool.pdm.scripts]
jupyter = "jupyter notebook --allow-root --no-browser --ip 0.0.0.0 --NotebookApp.token='' notebook"
lint = {composite = ["black", "isort", "ruff", "mypy --strict"]} # pdm run lint notebook

[tool.black]
line-length = 100
quiet = true

[tool.isort]
quiet = true
line_length = 100
multi_line_output = 3
profile = "black"

[tool.ruff]
fix = true
line-length = 100
target-version = "py311"

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
